[package]
name = "bevy_screen_diagnostics"
description = "Bevy plugin for displaying diagnostics on scren."
documentation = "https://docs.rs/bevy_screen_diagnostics"
version = "0.1.0"
license = "MIT OR Apache-2.0"
edition = "2021"
keywords = ["gamedev", "bevy", "diagnostics", "debug"]
repository = "https://github.com/laundmo/bevy_screen_diagnostics"
readme = "README.md"
authors = ["laundmo"]

[dependencies]
bevy = { version = "0.8.0", default-features = true }

[dev-dependencies]
bevy = { version = "0.8.0", default-features = true }

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
